dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker-compose -f docker-compose-pbf.yml build
      - travis_wait 90 docker-compose -f docker-compose-pbf.yml run builder
      - tar -czvf ukraine-latest.tar.gz output/ukraine-latest-fixed-crimea.osm.pbf
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "output/ukraine-latest-fixed-crimea.osm.pbf"
  skip_cleanup: true
  on:
    tags: true
